const { createCanvas } = require('canvas');
const fs = require('fs');

function createBratImage(text) {
    // Create canvas
    const width = 800;
    const height = 400;
    const canvas = createCanvas(width, height);
    const ctx = canvas.getContext('2d');

    // Set background (white)
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, width, height);

    // Set text style (black text, bold font)
    ctx.fillStyle = '#000000';
    ctx.font = 'bold 60px "Arial Black", Arial, sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';

    // Calculate text position
    const x = width / 2;
    const y = height / 2;

    // Draw text
    ctx.fillText(text, x, y);

    // Add "Brat" watermark
    ctx.font = '20px Arial';
    ctx.fillStyle = 'rgba(0, 0, 0, 0.5)';
    ctx.fillText('Generated by Brat', width - 150, height - 20);

    // Return as buffer
    return canvas.toBuffer('image/png');
}

// Example usage
const imageBuffer = createBratImage('Hai nama aku Putu');
fs.writeFileSync('brat-output.png', imageBuffer);
console.log('Image generated successfully!');

module.exports = createBratImage;
